### ISSUE TITLE
Fatal Error with WordPress 5.6.2

### ISSUE THREAD

**Issue by rontech2020** [hCaptcha/hcaptcha-wordpress-plugin#154]
Hello,

pretty urgent I think.

I have on 35 websites the hcapcha plugin, but it won't let me do it as it tells me there is this error: The plugin cannot be activated because it generates a fatal error.

You too from this problem?

How can I fix?

**Comment by e271828-** [comment]
@rontech2020 Do you have any more details on how to reproduce this, e.g. other plugins installed? 

I've tried just now on a clean 5.6.2 instance via Docker, and then enabled hCaptcha on some of the native pages like forgot password. Everything worked normally.


docker-compose.yml:

```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:5.6.2
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```
