### ISSUE TITLE
hCaptcha adds invalid inline CSS

### ISSUE THREAD

**Issue by rinart73** [hCaptcha/hcaptcha-wordpress-plugin#176]
The following CSS is incorrect because in CSS we can’t have nested elements like that (maybe you had SCSS but forgot to convert?). It results in CSS and HTML validation issues:
```css
div[style*="z-index: 2147483647"] {
  div[style*="border-width: 11px"][style*="position: absolute"][style*="pointer-events: none"] {
    border-style: none;
  }
}
```
https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/05803abad6c9222d5712996a3794a34423557fb4/src/php/Main.php#L134
