### ISSUE TITLE
Make the captcha responsive on screens < 500px width

### ISSUE THREAD

**Issue by valh1996** [hCaptcha/hcaptcha-wordpress-plugin#220]
A bit of css code should correct the problem:

```css
@media (max-width: 500px) {
  .h-captcha {
    transform: scale(0.77);
    transform-origin: 0 0;
  }
}
```
